x-healthcheck: &healthcheck
  timeout: 5s
  interval: 5s
  retries: 10

services:
  telegram-postman-proxy-bot:
    image: docker.io/library/node:18.4.0-alpine3.15
    command: sh -c "npm install && npm start"
    working_dir: /app
    environment:
      PORT: 80
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      PINNED_MESSAGE_ID: ${PINNED_MESSAGE_ID}
      LOCALE: ${LOCALE}
      TIMEZONE: ${TIMEZONE}
    healthcheck:
      <<: *healthcheck
      test: wget --quiet --spider http://localhost/api/health/check
    volumes:
      - .:/app
    ports:
      - ${PORT}:80
